name: ExamplePlugin
version: "1.2-Alpha"

main: ifteam\example\ExamplePlugin
api: [1.12.0]

author: ExampleDeveloper
website: "http://mcpekorea.com"

permissions:
  example:
    description: "ExamplePlugin"
    default: true