name: ExamplePlugin
main: ExamplePlugin\ExamplePlugin
version: 1.2-Alpha
author: ExampleMaker
api:
- 1.12.0
- 1.13.0
- 2.0.0

permissions:
 example:
  descript: "example permission"
  default: true